version: 2.1

jobs:
  build:
    docker:
      - image: cimg/android:2023.08 # Sudah termasuk Java 17 dan Android SDK
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk
    steps:
      - checkout

      - run:
          name: Show Java Version (Verifikasi Java 17)
          command: java -version

      - restore_cache:
          key: android-orb-v1-

      - run:
          name: Chmod Gradle Wrapper
          command: chmod +x ./gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: android-orb-v1-{{ epoch }}
          paths:
            - ~/.android/build-cache
            - ~/.android/cache

      - run:
          name: Run Build
          command: ./gradlew build

      - store_artifacts: 
          path: app/build/reports
          destination: reports

      - run:
          name: Run Lint & Unit Tests
          command: ./gradlew lint test

      - store_test_results:
          path: app/build/test-results

      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
